apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-microservice
  template:
    metadata:
      labels:
        app: sample-microservice
    spec:
      containers:
      - name: sample-microservice
        image: holuphilix/sample-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000